apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:mbunwe-victor/my-argocd-demo.git
    targetRevision: main
    path: charts/argocd-demo
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
